[project]
name = "bioinformatics-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "ipykernel>=7.2.0",
    "pandas>=3.0.3",
    "pandera[pandas]>=0.31.1",
    "pip>=26.1.1",
    "pytest>=9.0.3",
    "pyyaml>=6.0.3",
    "rdkit>=2026.3.1",
    "scikit-learn>=1.8.0",
    "torch>=2.11.0",
    "uvicorn>=0.47.0",
]
[tool.fastapi]
entrypoint = "src.backend.app:app"
